---
title: "Project description"
---

## Timeline

[Topic ideas](#topic-ideas) due Fri, Feb 18

[Proposal](#project-proposal) due Fri, Mar 18

[Draft report](#draft-report) due Fri, Apr 8

[Peer review](#peer-review) due Fri, Apr 15

[Final report](#written-report) due Mon, Apr 25

[Final GitHub repo](#reproducibility---organization) due Thu, Apr 28

## Introduction

**TL;DR**: *Pick a data set and do a demand analysis. That is your final project.*

The goal of the final project is for you to use aggregate and/or disaggregate demand analysis to analyze a data set of your own choosing.
Choose the data based on your group's interests or work you all have done in other courses or research projects.
The goal of this project is for you to demonstrate proficiency in the techniques we have covered in this class (and beyond, if you like!) and apply them to a data set to analyze it in a meaningful way.

All analyses must be done in Python or R, and all components of the project **must be reproducible**.

### Logistics

You will work on the project with a partner, or in a group of three depending on class size.

The four primary deliverables for the final project are

-   A written, reproducible report detailing your analysis
-   A GitHub repository corresponding to your report
-   Formal peer review on another team's project

## Topic ideas {#topic-ideas}

Identify 2-3 data sets you're interested in potentially using for the final project.
If you're unsure where to find data, you can use the list of potential data sources in the [Tips + Resources](#tips--resources) section as a starting point.
It may also help to think of topics you're interested in investigating and find data sets on those topics.

The purpose of submitting project ideas is to give you time to find data for the project and to make sure you have a data set that can help you be successful in the project.
**Therefore, you must use one of the data sets submitted as a topic idea, unless otherwise notified to the course instructor.**

The data sets should meet the following criteria:

-   At least 500 observations

-   At least 10 columns

-   At least 6 of the columns must be useful and unique predictor variables.

    -   If you have multiple columns with the same information (e.g. "state abbreviation" and "state name"), then they are not unique predictors.

-   At least one variable that can be identified as a reasonable response variable.

    -   The response variable can be quantitative or categorical.

-   A mix of quantitative and categorical variables that can be used as predictors.

-   You may not use data that has previously been used in any course materials, or any derivation of data that has been used in course materials.

**Please ask the course instructor if you're unsure whether your data set meets the criteria.**

For each data set, include the following:

#### Introduction and data

-   State the source of the data set
-   Describe when and how it was originally collected (by the original data curator, not necessarily how you found the data)
-   Describe the observations and the general characteristics being measured in the data

#### Research question

-   Describe a research question you're interested in answering using this data.

## Project proposal {#project-proposal}

The purpose of the project proposal is to help you think about your analysis strategy early.

Include the following in the proposal:

### Section 1 - Introduction

The introduction section includes:

-   An introduction to the subject matter you're investigating
-   The motivation for your research question (citing any relevant literature)
-   The general research question you wish to explore
-   Your hypotheses regarding the research question of interest

### Section 2 - Data description

In this section, you will describe the data set you wish to explore.
This includes:

-   Description of the observations in the data set,
-   Description of how the data was originally collected (not how you found the data but how the original curator of the data collected it).

### Section 3 - Analysis approach

In this section, you will provide a brief overview of your analysis approach.
This includes:

-   Description of the response variable
-   Visualization and summary statistics for the response variable
-   List of variables that will be considered as predictors
-   Regression model technique (e.g., multiple linear regression, logistic regression, mixed logit discrete choice)

### Data dictionary (aka code book)

Submit a data dictionary for all the variables in your data set in the `README` of your project repo, in the `data` folder.
Link to this file from your proposal writeup.

### Submission

Push all of your final changes to the GitHub repo, and submit the PDF of your proposal to Canvas.

### Proposal grading

| Total                | 10 pts |
|----------------------|--------|
| **Introduction**     | 3 pts  |
| **Data description** | 2 pts  |
| **Analysis plan**    | 4 pts  |
| **Data dictionary**  | 1 pts  |

Each component will be graded as follows:

-   **Meets expectations (full credit)**: All required elements are completed and are accurate.
    The narrative is written clearly, all tables and visualizations are nicely formatted, and the work would be presentable in a professional setting.

-   **Close to expectations (half credit)**: There are some elements missing and/or inaccurate.
    There are some issues with formatting.

-   **Does not meet expectations (no credit)**: Major elements missing.
    Work is not neatly formatted and would not be presentable in a professional setting.

## Draft report {#draft-report}

The purpose of the draft report and peer review is to give you an opportunity to get early feedback on your analysis.
Therefore, the draft and peer review will focus primarily on the exploratory data analysis, modeling, and initial interpretations.

You do not need to submit the draft on Canvas.

Below is a brief description of the sections to focus on in the draft:

### Introduction and data

This section includes an introduction to the project motivation, data, and research question.
Describe the data and definitions of key variables.
It should also include some exploratory data analysis.
All of the EDA won't fit in the paper, so focus on the EDA for the response variable and a few other interesting variables and relationships.

### Methodology

This section includes a brief description of your modeling process.
Explain the reasoning for the type of model you're fitting, predictor variables considered for the model including any interactions.
Additionally, show how you arrived at the final model by describing the model selection process, any variable transformations (if needed), and any other relevant considerations that were part of the model fitting process.

### Results

In this section, you will output the final model and include a brief discussion of the model assumptions, diagnostics, and any relevant model fit statistics.

This section also includes initial interpretations and conclusions drawn from the model.

## Peer review {#peer-review}

Critically reviewing others' work is a crucial part of the scientific process, and STA 210 is no exception.
Each team will be assigned one other teams's projects to review.
Each team should push their draft to their GitHub repo by the due date.

Provide your review in the form of GitHub issues to your partner team's GitHub repo using the issue template provided.
The peer review will be graded on the extent to which it comprehensively and constructively addresses the components of the partner team's report: the research context and motivation, exploratory data analysis, modeling, interpretations, and conclusions.

### Pairings

| Team being reviewed | Reviewer     |
|---------------------|----------------|
| chaa_chaa_chaa      | yay_stats      |
| dekk                | chaa_chaa_chaa |
| eight               | dekk           |
| housecats           | eight          |
| krafthouse          | housecats      |
| rrawr               | krafthouse     |
| stat_over_flow      | rrawr          |
| yay_stats           | stat_over_flow |


### Process and questions

Spend \~30 mins to review each team's project.

-   Find your team name in the **Reviewer 1** column.
-   Find the name of the team to review in the **Team being reviewed** column.
-   Open the repo of the team you're reviewing, read their project draft, and browser around the rest of their repo.
-   Then, go to the Issues tab in that repo, click on New issue, and click on Get started for the Peer review issue. Fill out this issue, answering the following questions:

    -   Describe the goal of the project.

    -   Describe the data used or collected, if any.
        If the proposal does not include the use of a specific dataset, comment on whether the project would be strengthened by the inclusion of a dataset.

    -   Describe the approaches, tools, and methods that will be used.

    -   Is there anything that is unclear from the proposal?

    -   Provide constructive feedback on how the team might be able to improve their project.
        Make sure your feedback includes at least one comment on the statistical modeling aspect of the project, but do feel free to comment on aspects beyond the modeling.

    -   What aspect of this project are you most interested in and would like to see highlighted in the presentation.

    -   Provide constructive feedback on any issues with file and/or code organization.

    -   (Optional) Any further comments or feedback?

## Written report {#written-report}

Your written report must be reproducible.
All team members should contribute to the GitHub repository, with regular meaningful commits.


**You will submit the PDF of your final report on Canvas.**

The PDF you submit must match the files in your GitHub repository *exactly*.
The mandatory components of the report are below.
You are free to add additional sections as necessary.
The report, including visualizations, should be **no more than 15 pages long.** There is no minimum page requirement; however, you should comprehensively address all of the analysis and report.

Be selective in what you include in your final report.
The goal is to write a cohesive narrative that demonstrates a thorough and comprehensive analysis rather than explain every step of the analysis.

You are welcome to include an appendix with additional work at the end of the written report document.
The appendix should be neatly formatted and easy for the reader to navigate.
It is not included in the 15-page limit.

The written report is worth 40 points, broken down as follows

| Total                         | 40 pts |
|-------------------------------|--------|
| **Introduction/data**         | 6 pts  |
| **Methodology**               | 10 pts |
| **Results**                   | 14 pts |
| **Discussion + conclusion**   | 6 pts  |
| **Organization + formatting** | 4 pts  |

[Click here](/documents/project-report-rubric.pdf "Project rubric") for a PDF of the written report rubric.

### Introduction and data

This section includes an introduction to the project motivation, data, and research question.
Describe the data and definitions of key variables.
It should also include some exploratory data analysis.
All of the EDA won't fit in the paper, so focus on the EDA for the response variable and a few other interesting variables and relationships.

#### Grading criteria

The research question and motivation are clearly stated in the introduction, including citations for the data source and any external research.
The data are clearly described, including a description about how the data were originally collected and a concise definition of the variables relevant to understanding the report.
The data cleaning process is clearly described, including any decisions made in the process (e.g., creating new variables, removing observations, etc.) The explanatory data analysis helps the reader better understand the observations in the data along with interesting and relevant relationships between the variables.
It incorporates appropriate visualizations and summary statistics.

### Methodology

This section includes a brief description of your modeling process.
Explain the reasoning for the type of model you're fitting, predictor variables considered for the model including any interactions.
Additionally, show how you arrived at the final model by describing the model selection process, interactions considered, variable transformations (if needed), assessment of conditions and diagnostics, and any other relevant considerations that were part of the model fitting process.

#### Grading criteria

The analysis steps are appropriate for the data and research question.
The group used a thorough and careful approach to select the final model; the approach is clearly described in the report.
The model selection process took into account potential interaction effects and addressed any violations in model conditions.
The model conditions and diagnostics are thoroughly and accurately assessed for their model.
If violations of model conditions are still present, there was a reasonable attempt to address the violations based on the course content.

### Results

This is where you will output the final model with any relevant model fit statistics.

Describe the key results from the model.
The goal is not to interpret every single variable in the model but rather to show that you are proficient in using the model output to address the research questions, using the interpretations to support your conclusions.
Focus on the variables that help you answer the research question and that provide relevant context for the reader.

#### Grading criteria

The model fit is clearly assessed, and interesting findings from the model are clearly described.
Interpretations of model coefficients are used to support the key findings and conclusions, rather than merely listing the interpretation of every model coefficient.
If the primary modeling objective is prediction, the model's predictive power is thoroughly assessed.

### Discussion + Conclusion

In this section you'll include a summary of what you have learned about your research question along with statistical arguments supporting your conclusions.
In addition, discuss the limitations of your analysis and provide suggestions on ways the analysis could be improved.
Any potential issues pertaining to the reliability and validity of your data and appropriateness of the statistical analysis should also be discussed here.
Lastly, this section will include ideas for future work.

#### Grading criteria

Overall conclusions from analysis are clearly described, and the model results are put into the larger context of the subject matter and original research question.
There is thoughtful consideration of potential limitations of the data and/or analysis, and ideas for future work are clearly described.

### Organization + formatting

This is an assessment of the overall presentation and formatting of the written report.

#### Grading criteria

The report neatly written and organized with clear section headers and appropriately sized figures with informative labels.
Numerical results are displayed with a reasonable number of digits, and all visualizations are neatly formatted.
All citations and links are properly formatted.
If there is an appendix, it is reasonably organized and easy for the reader to find relevant information.
All code, warnings, and messages are suppressed.
The main body of the written report (not including the appendix) is no longer than 10 pages.

## Reproducibility + organization

All written work should be reproducible and the GitHub repo should be neatly organized.

The GitHub repo should have the following structure:

-   `README`: Short project description and data dictionary

-   `written-report.qmd` & `written-report.pdf`: Final written report

-   `/data`: Folder that contains the data set for the final project.

-   `/previous-work`: Folder that contains the `topic-ideas` and `project-proposal` files.

Points for reproducibility + organization will be based on the reproducibility of the written report and the organization of the project GitHub repo.
The repo should be neatly organized as described above, there should be no extraneous files, all text in the README should be easily readable.

## Overall grading

The grade breakdown is as follows:

| Total                              | 100 pts |
|------------------------------------|---------|
| **Topic ideas**                    | 5 pts   |
| **Project proposal**               | 10 pts  |
| **Peer review**                    | 10 pts  |
| **Written report**                 | 40 pts  |
| **Slides + video presentation**    | 20 pts  |
| **Reproducibility + organization** | 5 pts   |
| **Video comments**                 | 5 pts   |
| **Peer teamwork evaluation**       | 5 pts   |

*Note: No late project reports are accepted.*

### Grading summary

Grading of the project will take into account the following:

-   Content - What is the quality of research and/or policy question and relevancy of data to those questions?
-   Correctness - Are statistical procedures carried out and explained correctly?
-   Writing and Presentation - What is the quality of the statistical presentation, writing, and explanations?
-   Creativity and Critical Thought - Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

A general breakdown of scoring is as follows:

-   *90%-100%*: Outstanding effort. Student understands how to apply all statistical concepts, can put the results into a cogent argument, can identify weaknesses in the argument, and can clearly communicate the results to others.
-   *80%-89%*: Good effort. Student understands most of the concepts, puts together an adequate argument, identifies some weaknesses of their argument, and communicates most results clearly to others.
-   *70%-79%*: Passing effort. Student has misunderstanding of concepts in several areas, has some trouble putting results together in a cogent argument, and communication of results is sometimes unclear.
-   *60%-69%*: Struggling effort. Student is making some effort, but has misunderstanding of many concepts and is unable to put together a cogent argument. Communication of results is unclear.
-   *Below 60%*: Student is not making a sufficient effort.

### Late work policy

**There is no late work accepted on this project.** Be sure to turn in your work early to avoid any technological mishaps.
