---
title: "Disaggregate Demand Model Assignment"
---

## Assignment description
The objective of this assignment is to familiarize you with the estimation and analysis of discrete choice demand models. A dataset of observed commuting mode choice is [available in MS Excel format](https://github.com/Hawkins-TECH-Lab/ENCI707/blob/d1aa920232070ad51cbb19e2afe55499172e2648/assignment-data/WeeklyModeChoiceDATA-MondayCommuting.xlsx). The dataset contains details on eight modes and various sociodemographic details for each individual. The assignment is due Mar. 19 by 11:59 PM on D2L. The assignment should be completed in groups of 2-3 persons. You may choose your own group. Your group does not need to be the same as prior assignments.

1. Develop an multinomial logit (MNL) model of commuting mode choice.
2. Perform model validation. This validation could comprise bootstrap resampling, cross-valdiation, or any other similar method.
3. Estimate direct elasticities of level-of-service variables.

The assignment deliverable should have the form of a professional report and should not be more than 10 pages (singles-spaced).

## Overall grading

The grade breakdown is as follows:

| Total                              | 25 pts  |
|------------------------------------|---------|
| **Introduction**                   | 5 pts   |
| **Correct model interpretation**   | 10 pts  |
| **Includes all required elements** | 5 pts   |
| **Formatting and report quality**  | 10 pts  |

### Grading summary

A general breakdown of scoring is as follows:

-   *90%-100%*: Outstanding effort. Students understand how to apply all statistical concepts, can put the results into a cogent argument, can identify weaknesses in the argument, and can clearly communicate the results to others.
-   *80%-89%*: Good effort. Students understand most of the concepts, put together an adequate argument, identify some weaknesses of their argument, and communicate most results clearly to others.
-   *70%-79%*: Passing effort. Students have misunderstanding of concepts in several areas, have some trouble putting results together in a cogent argument, and communication of results is sometimes unclear.
-   *60%-69%*: Struggling effort. Students are making some effort, but have misunderstanding of many concepts and are unable to put together a cogent argument. Communication of results is unclear.
-   *Below 60%*: Students are not making a sufficient effort.