---
title: "Survey Design Assignment"
---

## Assignment description
The objective of this assignment is to familiarize you with the process of developing a survey instrument. The assignment is due Feb. 07 by 11:59 PM on D2L. The assignment should be completed in groups of 2-3 persons. You may choose your own group.

You have been tasked by the Province of Alberta to develop a survey to understand the demand for travel between Calgary and Banff as part of their provincial rail strategy. You final deliverable is a survey provided in text format. Your survey must include the following general elements for each survey respondent, but the details of the question text and scope is left to your group.

1. Demographics.
2. Current travel frequency and mode to/from Banff, Alberta.
3. Attitudes about passenger rail between Calgary and Banff.
4. A stated preference experiment. The experiment must include at least two modes and at least two attributes for each mode. Each attribute must have at least two levels. You should provide an illustration in the form of a table.


## Overall grading

The grade breakdown is as follows:

| Total                              | 25 pts  |
|------------------------------------|---------|
| **Demographics are relevant and complete**   | 5 pts   |
| **Travel pattern data are complete and capture necessary details to plan for passenger rail**   | 10 pts  |
| **Stated preference experiment is described in full. Attributes are relevant and their levels are reasonable.** | 10 pts   |
| **Formatting and survey quality**  | 5 pts  |

### Grading summary

A general breakdown of scoring is as follows:

-   *90%-100%*: Outstanding effort. Students understand all survey concepts, understand the study needs, and can formulate clear questions.
-   *80%-89%*: Good effort. Students understand most survey concepts, understand the study needs, and can formulate mostly clear questions.
-   *70%-79%*: Passing effort. Students have some misunderstandings about survey concepts, miss elements of the study needs, and/or questions are poorly worded.
-   *60%-69%*: Struggling effort. Students are making some effort, but have misunderstanding of many concepts and are unable to put together a cogent survey.