---
title: "Potential Project Topics"
format: html
---

You are welcome to select your own term paper topic. However, I have several partially complete research papers that students are encouraged to take on as a term paper. The benefit of this approach is that the data and initial analysis have been completed. A draft manuscript is also available. However, taking on an existing research project means the student will be expected to implement improvements to completion and participate in subsequent revisions.

The first two projects implement pseudo-panel methods to expenditure research questions.
1. E-shopping demand analysis using PSRC travel diary data. This is joint work with Dr. Usman Ahmed at the University of Tennessee, Knoxville. The objective of this research is to understand variations in e-shopping frequency pre-, during-, and post-COVID. Initial analysis used an ordered probit model. Your task would be to replace the model with a negative binomial specification with observation duration adjustment. Additional details would be formulated through meetings with Dr. Ahmed and myself.
2. Travel expenditure analysis using the US Consumer Expenditure Survey. This is joint work with Dr. Sami Hasnine at Virginia Tech. The objective of the research is to understand demographic drivers of transportation expenditure. Initial analysis was conducted using a Cobb-Douglas demand specification. The proposed method is an almost ideal demand system (AIDS) model.

Other topics that could be explored by students.
3. Environmental economics or non-market valuation topics using a dataset from [here](https://czaj.org/research/supplementary-materials).
4. Travel behaviour or demand research questions using the City of Calgary travel diary. Potential focus areas are the effect of weather condition variation over the year on travel choices or calibration of travel demand models estimated from travel diary data collected over a year.
5. Implementation of models from my [goal pursuit theory (GPT) paper](https://arxiv.org/abs/2606.29145).