---
title: "Application Exercise 4 - Statistics Activity"
sidebar: ENCI707
---

::: callout-important
This application exercise should be submitted via D2L by end of the day on which it was introduced in lecture.
:::

We can demonstrate several problems with statistical comparisons using the example of a research article published in a leading journal of psychology. The article begins:

"Each month many women experience an ovulatory cycle that regulates fertility. Whereas research finds
that this cycle influences women’s mating preferences, we propose that it might also change women’s
political and religious views. Building on theory suggesting that political and religious orientation are
linked to reproductive goals, we tested how fertility influenced women’s politics, religiosity, and voting
in the 2012 U.S. presidential election. In two studies with large and diverse samples, ovulation had
drastically different effects on single versus married women. Ovulation led single women to become
more liberal, less religious, and more likely to vote for Barack Obama. In contrast, ovulation led married
women to become more conservative, more religious, and more likely to vote for Mitt Romney. In
addition, ovulatory-induced changes in political orientation mediated women’s voting behavior. Overall,
the ovulatory cycle not only influences women’s politics, but appears to do so differently for single versus
married women."

<!-- One problem here is that there are so many different things that could be compared, but all we see
is some subset of the comparisons. Some of the choices available in this analysis include the days
of the month characterized as peak fertility, the dividing line between single and married (in this
particular study, unmarried but partnered women were counted as married), data exclusion rules
based on reports of menstrual cycle length and timing, and the decision of which interactions to study.
Given all these possibilities, it is no surprise at all that statistically significant comparisons turned up;
this would be expected even were the data generated purely by noise.
In addition, relative to our understanding of the vast literature on voting behavior, the claimed
effects seem implausibly large—a type M error. For example, the paper reports that, among women
in relationships, 40% in the ovulation period supported Romney, compared to 23% in the non-fertile
part of their cycle. Given that opinion polls find very few people switching their vote preferences
during the campaign for any reason, these numbers seem unrealistic. The authors might respond that
they don’t care about the magnitude of the difference, just the sign, but (a) with a magnitude of this
size, we are talking noise (not just sampling error but also errors in measurement), and (b) one could
just as easily explain this as a differential nonresponse pattern: maybe liberal or conservative women
in different parts of their cycle are more or less likely to participate in a survey. It would be easy
enough to come up with a story about that.
As researchers and as evaluators of the research of others, we need to avoid the trap of considering
this sort of small study as providing definitive evidence—even if certain comparisons happen to be
statistically significant. -->