---
title: "Bikeshare in Lincoln"
sidebar: Project
section-divs: true
echo: false

---
```{python}
import pandas as pd
import folium


```


## Map of Lincoln showing all the bikeshare stations

```{python}
import json

with open("data/lincoln/kiosks_lincoln.json", "r") as f:
    coords = json.load(f)



mymap = folium.Map(location=[40.81712,-96.70084], zoom_start=14)

# Add markers for each coordinate
for kiosk, coord in coords.items():
    lat, lon = map(float, coord.split(','))
    folium.Marker([lat, lon], popup=kiosk).add_to(mymap)


mymap


```

## Most used stations graph

```{python}
import plotly.express as px

df = pd.read_csv("data/lincoln/LNK_Bike_Trips_wt_avg_time_bin.csv")

# Sort the DataFrame by 'Total_Trips' column
df_sorted = df.sort_values(by='Total_Trips', ascending=False)

# Select the top 15 rows
top_kiosks = df_sorted.head(20)

# Plot using Plotly
fig = px.bar(top_kiosks, x='Checkout_Kiosk_Coordinates', y='Total_Trips',)

# rename the x-axis label
fig.update_xaxes(title_text='Checkout Station Address')

# rename the y-axis label
fig.update_yaxes(title_text='Total Trips')

# change the angle of the x-axis labels
fig.update_layout(xaxis_tickangle=-45)


fig.show()


```

# Bikeshare Vs. Transit
For both Lincoln and Omaha, we were interested in how long it would take to make bikeshare trips by transit. We used Google Directions API with the origin and destination station locations for trips (excluding those starting and ending at the same station). The results are enlightening and suggest bikeshare could provide a good complement for transit where trip lengths are short or trip density is low, such that running large buses would be inefficient. The results for Lincoln are summarized below. Note: these results do not fully capture wait time induced by high headway (i.e., low frequency) bus service on most routes in both cities. For example, the bus running near Dr. Hawkins' house runs once per hour, whereas a bike would (fingers crossed) be immediately available if there was a bikeshare station at this location.

| Bikeshare:Transit Ratio (<1.0 = bikeshare faster than transit) |
|-------------------------|------|
| Minimum ratio           | 0.44 |
| Maximum ratio           | 0.92 |
| Mean ratio              | 0.61 |
| Median ratio            | 0.57 |