---
title: "CIVE461"
sidebar: CIVE461
tbl-colwidths: [5,10,30,5,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the semester.
Note that this schedule will be updated as the semester progresses, with all changes documented here.

::: column-screen-inset-right
|           Week            | Date        | Topic                                               |                             Prepare                             |                                   Slides                                   				|                                                       AE                                                        |                                                                                       HW                                                                                       |                            Exam                            |
|:------:|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
|  [1](/teaching/CIVE461/weeks/week-1.html)  | Mon, Aug 21  | Welcome to CIVE 461!                               | [📖](/teaching/CIVE461/weeks/week-1.html#prepare){aria-label="Week  summary"}    |      				 																      |               |                                                                                                                                   |															|
|                           | Wed, Aug 23  | Introduction to transportation planning			|                                                                 |[🖥️](/teaching/CIVE461/slides/lec-1.html "Lecture slides"){aria-label="Lecture 1 slides"}  |       [📋](/teaching/CIVE461/ae/ae-0-travel-diary.html "Application exercise"){aria-label="Application Exercise 0 instructions"}       |                                                                                                                                                                                |                                                            |
|  [2](/teaching/CIVE461/weeks/week-2.html)  | Mon, Aug 28 | Statistics											|  [📖](/teaching/CIVE461//weeks/week-2.html#prepare){aria-label="Week 2 summary"}  | [🖥️](/teaching/CIVE461/slides/lec-2.html "Lab slides"){aria-label="Lab 2 slides"}      |                                                                                                                 |                                                                                                                                                                                |                                                            |
|                           | Wed, Aug 30 | Statistical modeling								|  																  |  																						  |                                                                                                                 |                                                                                                                                                                                |                                                            |
|  [3](/teaching/CIVE461/weeks/week-3.html)  | Mon, Sep 04 | *Labor Day*											| [📖](/teaching/CIVE461/weeks/week-3.html#prepare){aria-label="Week 3 summary"}   |                                                                            |                                                                                                                 |                                                                                                                                                                                |                                                            |
|                           | Wed, Sep 06 | Statistical modeling						|    															  |    |    [📋](/teaching/CIVE461/ae/ae-1-transportation-planning-experience.html "Application exercise"){aria-label="Application Exercise 1 instructions"}     |                                                                                                                                                                                |                                                            |
|  [4](/teaching/CIVE461/weeks/week-4.html)  | Mon, Sep 11 | Programming in Python								| [📖](/teaching/CIVE461/weeks/week-4.html#prepare){aria-label="Week 4 summary"}   |             |                                                                                                                 |                                                                                                                                                                                |                                                            |
|                           | Wed, Sep 13 | Trip generation										|    															  |  [🖥️](/teaching/CIVE461/slides/lec-3.html "Lecture slides"){aria-label="Lecture 3 slides"}  |   [📋](/teaching/CIVE461/ae/ae-2-statistics.html "Application exercise"){aria-label="Application Exercise 2 instructions"}                                                                                                              |                                                                                                                                                                                |                                                            |
|  [5](/teaching/CIVE461/weeks/week-5.html)  | Mon, Sep 18 | Trip generation										|   [📖](/teaching/CIVE461/weeks/week-5.html#prepare){aria-label="Week 5 summary"} |      																				      |                                                                                                                 |                                                                                                                                                                                |                                                            |
|                           | Wed, Sep 20  | Trip generation									|   															  |  																						  |                                                                                                                 |                                                                                                                                                                                |                                                            |
|  [6](/teaching/CIVE461/weeks/week-6.html)  | Mon, Sep 25  | 	Trip generation						| [📖](/teaching/CIVE461/weeks/week-6.html#prepare){aria-label="Week 6 summary"}   |                                                                            |                                                                                                                 |                                                                                                                                                                                |                                                            |
|                           | Wed  Sep 27 | Transportation planning process, regulation, and data						|                                                                 |           [🖥️](/teaching/CIVE461/slides/lec-4.html "Lecture slides"){aria-label="Lecture 4 slides"}                                                                 |            [📋](/teaching/CIVE461/ae/ae-3-transport-plans.html){aria-label="Application Exercise 3 instructions"}                                                                                                     |                                                                                                                                                                        [✍️](/teaching/CIVE461/project/project-description.html#report-1)        |  |
|  [7](/teaching/CIVE461/weeks/week-7.html)  | Mon, Oct 02 | Transportation planning process, regulation, and data		| [📖](/teaching/CIVE461/weeks/week.html#prepare){aria-label="Week 7 summary"}   |                                                                            |                                                                                                                 |                                                                                                                                                                                |                                                            |
|                           | Wed, Oct 04 | Trip distribution									|    															  | 				[🖥️](/teaching/CIVE461/supplemental/trip-distribution.html "Supplemental slides"){aria-label="Supplemental slides 1"}																		 |    [📋](/teaching/CIVE461/ae/ae-4-trip-distribution.html){aria-label="Application Exercise 4 instructions"}      |                                                                                                                                                                                |                                                            |
|  [8](/teaching/CIVE461/weeks/week-8.html)  | Mon, Oct 09 | Trip distribution									|  [📖](/teaching/CIVE461/weeks/week-8.html#prepare){aria-label="Week 8 summary"}  |                                                                            |                                                                                                                 |                                                                                                                                                                                |                                                            |
|                           | Wed, Oct 11 | Trip distribution								|    															  |  |       |                                                                                                                                                                                |                                                            |
|  [9](/teaching/CIVE461/weeks/week-9.html)  | Mon, Oct 16 | *Fall break**										| [📖](/teaching/CIVE461/weeks/week-9.html#prepare){aria-label="Week 9 summary"}   |                                                                            |                                                                                                                 |                                                                                                                                                                                |                                                            |
|                           | Wed  Oct 18 |  				Guest lecture						|                                                                 |                                                                            |                                                                                                                 |                                                                                                                                                                                |  |
| [10](/teaching/CIVE461/weeks/week-10.html) | Mon, Oct 23 | 		Choice models					| [📖](/teaching/CIVE461/weeks/week-10.html#prepare){aria-label="Week 10 summary"}  |  [🖥️](/teaching/CIVE461/slides/lec-5.html "Lecture slides"){aria-label="Lecture 5 slides"}                                                                          |                                                                                                                 |                                                                      [✍️](/teaching/CIVE461/project/project-description.html#report-2)                                                                                                          |                                                            |
|                           | Wed, Oct 25 | 			Programming choice models				|  																	| 																							 |                |                                                                                                                                                                                |                                                            |
| [11](/teaching/CIVE461/weeks/week-11.html) | Mon, Oct 30 | 			Mode and destination choice				| [📖](/teaching/CIVE461/weeks/week-11.html#prepare){aria-label="Week 11 summary"}  |          [🖥️](/teaching/CIVE461/slides/lec-6.html "Lecture slides"){aria-label="Lecture 6 slides"}                                                                  |                                                                                                                 |                                     [✍️](/teaching/CIVE461/assignments/indiv_assignment1.html)                                                                                                                                           |                                                            |
|                           | Wed, Nov 01 | 			Mode and destination choice							| 																	|  |                                                                                                                 |                                                                                                                                                                                |                                                            |
| [12](/teaching/CIVE461/weeks/week-12.html) | Mon, Nov 06 | 			Transportation equity							| [📖](/teaching/CIVE461/weeks/week-12.html#prepare){aria-label="Week 12 summary"} |                                                                            |                                                                                                                 |                                                                                                                                                                                |                                                            |
|                           | Wed, Nov 08 | Trip assignment										|  																| 			[🖥️](/teaching/CIVE461/slides/lec-7.html "Lecture slides"){aria-label="Lecture 7 slides"}																					 |                                                                                                                 |                                                                                                                                                                   [✍️](/teaching/CIVE461/project/project-description.html#report-3)             |                                                            |
| [13](/teaching/CIVE461/weeks/week-13.html) | Mon, Nov 13  | 	Trip assignment								| [📖](/teaching/CIVE461/weeks/week-13.html#prepare){aria-label="Week 13 summary"}  |                                                                            |                                                                                                                 |                                                                                                                                                                                |                                                            |
|                           | Wed, Nov 15  | Trip assignment									|  																| 																								 |                                                                        |										|                                                                                                                                                                                |                                                           |
| [14](/teaching/CIVE461/weeks/week-14.html) | Mon, Nov 20 | Freight modeling									| [📖](/teaching/CIVE461/weeks/week-14.html#prepare){aria-label="Week 14 summary"}      |                                                                            |                                                                                                                 |                                                                       [✍️](/teaching/CIVE461/assignments/indiv_assignment2.html)                                                                                                         |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
|                           | Wed  Nov 22         | *Thanksgiving break*						|                                                                 |                                                                            |                                                                                                                 |                                                                                                                                                                                |  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
| [15](/teaching/CIVE461/weeks/week-15.html) | Mon, Nov 27 | Freight modeling									| [📖](/teaching/CIVE461/weeks/week-15.html#prepare){aria-label="Week 15 summary"} |                                                                            |                                                                                                                 |                                                                                                                                                                                |                                                            |
|                           | Wed, Nov 28 | Land use planning							|                                                                 |                                                                            |                                                                                                                 |                                 [✍️](/teaching/CIVE461/project/project-description.html#final-report)                                                                                                                                               |                                                            |
| [16](/teaching/CIVE461/weeks/week-16.html) | Mon, Dec 04 | Review							| [📖](/teaching/CIVE461/weeks/week-16.html#prepare){aria-label="Week 16 summary"}    |                                                                            |                                                                                                                 |                                                                                                                                                                                |                                                            |
|                           | Wed, Dec 06 | Review													|                                                                 |                                                                            |                                                                                                                 |                                                                                                                                                                                |                                                            |
:::
